from datetime import datetime

question_set = {
    "forecast_questions": [
        # 🌍 Geopolitics (4 questions)
        {
            "question": "Will Russia invade Ukraine (crossing into uncontested Ukrainian territory) in 2022?",
            "resolution_criteria": "Russian armed forces enter Ukrainian territory beyond Donbas/Crimea",
            "date_created": datetime.date(2022, 2, 1),
            "resolution_date": datetime.date(2022, 2, 24),
            "outcome": 1.0,
            "estimated_prior": 0.60,
            "contamination_risk": 3,
        },
        {
            "question": "Will Ukraine retain control of Kyiv through end of 2022?",
            "resolution_criteria": "Ukrainian government operates from Kyiv without capitulation",
            "date_created": datetime.date(2022, 2, 28),
            "resolution_date": datetime.date(2022, 12, 31),
            "outcome": 1.0,
            "estimated_prior": 0.45,
            "contamination_risk": 3,
        },
        {
            "question": "Will China conduct major military exercises near Taiwan in 2022 (in response to US/Taiwan actions)?",
            "resolution_criteria": "PLA conducts announced live-fire exercises in Taiwan Strait",
            "date_created": datetime.date(2022, 7, 1),
            "resolution_date": datetime.date(2022, 8, 4),
            "outcome": 1.0,
            "estimated_prior": 0.55,
            "contamination_risk": 2,
        },
        {
            "question": "Will Iran and Saudi Arabia restore diplomatic relations in 2023?",
            "resolution_criteria": "Both countries announce resumption of diplomatic ties / reopen embassies",
            "date_created": datetime.date(2023, 1, 1),
            "resolution_date": datetime.date(2023, 3, 10),
            "outcome": 1.0,
            "estimated_prior": 0.15,
            "contamination_risk": 2,
        },
        # 🏢 Business & Corporate (6 questions)
        {
            "question": "Will Disney+ surpass Netflix in total global subscribers by end of 2022?",
            "resolution_criteria": "Disney reports 220M+ subscribers (vs. Netflix's count at same period)",
            "date_created": datetime.date(2022, 1, 1),
            "resolution_date": datetime.date(2022, 12, 31),
            "outcome": 0.0,
            "estimated_prior": 0.25,
            "contamination_risk": 2,
        },
        {
            "question": "Will Peloton's stock price decline more than 50% from its January 2021 high by end of 2021?",
            "resolution_criteria": "PTON trades at ≤50% of its Jan 2021 peak within the calendar year",
            "date_created": datetime.date(2021, 4, 1),
            "resolution_date": datetime.date(2021, 12, 31),
            "outcome": 1.0,
            "estimated_prior": 0.20,
            "contamination_risk": 2,
        },
        {
            "question": "Will Amazon acquire MGM Studios in 2022?",
            "resolution_criteria": "DOJ/FTC clears deal and transaction closes",
            "date_created": datetime.date(2022, 1, 1),
            "resolution_date": datetime.date(2022, 3, 17),
            "outcome": 1.0,
            "estimated_prior": 0.72,
            "contamination_risk": 1,
        },
        {
            "question": "Will Microsoft's acquisition of Activision Blizzard close in 2023?",
            "resolution_criteria": "Deal closes and Microsoft takes ownership",
            "date_created": datetime.date(2023, 1, 1),
            "resolution_date": datetime.date(2023, 10, 13),
            "outcome": 1.0,
            "estimated_prior": 0.45,
            "contamination_risk": 2,
        },
        {
            "question": "Will Bed Bath & Beyond file for bankruptcy in 2023?",
            "resolution_criteria": "BBBY files for Chapter 11",
            "date_created": datetime.date(2023, 1, 1),
            "resolution_date": datetime.date(2023, 4, 23),
            "outcome": 1.0,
            "estimated_prior": 0.62,
            "contamination_risk": 1,
        },
        {
            "question": "Will Adobe's proposed acquisition of Figma close in 2023?",
            "resolution_criteria": "Deal closes, or Adobe abandons the acquisition",
            "date_created": datetime.date(2023, 6, 1),
            "resolution_date": datetime.date(2023, 12, 18),
            "outcome": 0.0,
            "estimated_prior": 0.45,
            "contamination_risk": 1,
        },
        # 🏛️ Politics & Elections (12 questions)
        {
            "question": "Will Republicans win control of the US Senate in the 2022 midterm elections?",
            "resolution_criteria": "Republicans hold 51+ seats after all races are called",
            "date_created": datetime.date(2022, 9, 1),
            "resolution_date": datetime.date(2022, 11, 14),
            "outcome": 0.0,
            "estimated_prior": 0.55,
            "contamination_risk": 3,
        },
        {
            "question": "Will Republicans win control of the US House in the 2022 midterm elections?",
            "resolution_criteria": "Republicans hold 218+ seats after all races are called",
            "date_created": datetime.date(2022, 9, 1),
            "resolution_date": datetime.date(2022, 11, 17),
            "outcome": 1.0,
            "estimated_prior": 0.72,
            "contamination_risk": 3,
        },
        {
            "question": "Will Lula win the 2022 Brazilian presidential election?",
            "resolution_criteria": "Lula declared winner in first or second round",
            "date_created": datetime.date(2022, 9, 1),
            "resolution_date": datetime.date(2022, 10, 30),
            "outcome": 1.0,
            "estimated_prior": 0.55,
            "contamination_risk": 3,
        },
        {
            "question": "Will Emmanuel Macron win re-election in the 2022 French presidential election?",
            "resolution_criteria": "Macron wins the runoff vote",
            "date_created": datetime.date(2022, 3, 1),
            "resolution_date": datetime.date(2022, 4, 24),
            "outcome": 1.0,
            "estimated_prior": 0.68,
            "contamination_risk": 3,
        },
        {
            "question": "Will Donald Trump win the 2024 US presidential election?",
            "resolution_criteria": "Trump wins 270+ Electoral College votes",
            "date_created": datetime.date(2024, 9, 1),
            "resolution_date": datetime.date(2024, 11, 6),
            "outcome": 1.0,
            "estimated_prior": 0.48,
            "contamination_risk": 3,
        },
        {
            "question": "Will Labour win the 2024 UK general election with a parliamentary majority?",
            "resolution_criteria": "Labour wins 326+ seats",
            "date_created": datetime.date(2024, 5, 1),
            "resolution_date": datetime.date(2024, 7, 4),
            "outcome": 1.0,
            "estimated_prior": 0.80,
            "contamination_risk": 3,
        },
        {
            "question": "Will the UK have more than one Prime Minister in 2022?",
            "resolution_criteria": "A new PM takes office after Boris Johnson",
            "date_created": datetime.date(2022, 7, 10),
            "resolution_date": datetime.date(2022, 12, 31),
            "outcome": 1.0,
            "estimated_prior": 0.85,
            "contamination_risk": 3,
        },
        {
            "question": "Will Finland formally join NATO in 2023?",
            "resolution_criteria": "Finland's accession ratified and deposited",
            "date_created": datetime.date(2023, 1, 1),
            "resolution_date": datetime.date(2023, 4, 4),
            "outcome": 1.0,
            "estimated_prior": 0.78,
            "contamination_risk": 2,
        },
        {
            "question": "Will Sweden formally join NATO by end of 2024?",
            "resolution_criteria": "Sweden's accession ratified and deposited",
            "date_created": datetime.date(2023, 6, 1),
            "resolution_date": datetime.date(2024, 3, 7),
            "outcome": 1.0,
            "estimated_prior": 0.62,
            "contamination_risk": 2,
        },
        {
            "question": "Will Jair Bolsonaro accept the result of the 2022 Brazilian election?",
            "resolution_criteria": "Bolsonaro publicly concedes or power transfers without a coup attempt before Feb 1, 2023",
            "date_created": datetime.date(2022, 10, 31),
            "resolution_date": datetime.date(2023, 1, 31),
            "outcome": 1.0,
            "estimated_prior": 0.45,
            "contamination_risk": 2,
        },
        {
            "question": "Will Georgia hold a runoff Senate election in January 2021?",
            "resolution_criteria": "Both GA Senate races go to runoff",
            "date_created": datetime.date(2020, 11, 4),
            "resolution_date": datetime.date(2020, 11, 5),
            "outcome": 1.0,
            "estimated_prior": 0.70,
            "contamination_risk": 3,
        },
        {
            "question": "Will Democrats win both Georgia Senate seats in the January 2021 runoff?",
            "resolution_criteria": "Both Warnock and Ossoff declared winners",
            "date_created": datetime.date(2020, 12, 1),
            "resolution_date": datetime.date(2021, 1, 6),
            "outcome": 1.0,
            "estimated_prior": 0.45,
            "contamination_risk": 3,
        },
        # 💰 Economics & Finance (10 questions)
        {
            "question": "Will US CPI inflation exceed 8% year-over-year in any month of 2022?",
            "resolution_criteria": "BLS reports any monthly CPI YoY figure ≥ 8.0%",
            "date_created": datetime.date(2022, 1, 1),
            "resolution_date": datetime.date(2022, 4, 12),
            "outcome": 1.0,
            "estimated_prior": 0.30,
            "contamination_risk": 3,
        },
        {
            "question": "Will the Federal Reserve raise interest rates at least 4 times in 2022?",
            "resolution_criteria": "Fed funds target range raised in 4+ FOMC meetings",
            "date_created": datetime.date(2022, 1, 1),
            "resolution_date": datetime.date(2022, 12, 14),
            "outcome": 1.0,
            "estimated_prior": 0.25,
            "contamination_risk": 3,
        },
        {
            "question": "Will the S&P 500 enter bear market territory (−20% from peak) in 2022?",
            "resolution_criteria": "S&P 500 closes 20%+ below its 2022 high at any point",
            "date_created": datetime.date(2022, 1, 1),
            "resolution_date": datetime.date(2022, 6, 13),
            "outcome": 1.0,
            "estimated_prior": 0.22,
            "contamination_risk": 3,
        },
        {
            "question": "Will Bitcoin's price exceed $60,000 USD at any point in 2021?",
            "resolution_criteria": "BTC/USD spot price on any major exchange ≥ $60,000",
            "date_created": datetime.date(2021, 1, 1),
            "resolution_date": datetime.date(2021, 3, 13),
            "outcome": 1.0,
            "estimated_prior": 0.35,
            "contamination_risk": 3,
        },
        {
            "question": "Will Bitcoin's price exceed $100,000 USD at any point in 2024?",
            "resolution_criteria": "BTC/USD spot price on any major exchange ≥ $100,000",
            "date_created": datetime.date(2024, 6, 1),
            "resolution_date": datetime.date(2024, 12, 5),
            "outcome": 1.0,
            "estimated_prior": 0.30,
            "contamination_risk": 2,
        },
        {
            "question": "Will Silicon Valley Bank (SVB) be acquired or taken over by regulators in 2023?",
            "resolution_criteria": "FDIC or acquirer takes control of SVB",
            "date_created": datetime.date(2023, 3, 8),
            "resolution_date": datetime.date(2023, 3, 10),
            "outcome": 1.0,
            "estimated_prior": 0.55,
            "contamination_risk": 2,
        },
        {
            "question": "Will the US officially enter a recession (two consecutive quarters of negative GDP growth) in 2022?",
            "resolution_criteria": "BEA reports negative real GDP growth in Q1 and Q2 2022",
            "date_created": datetime.date(2022, 4, 1),
            "resolution_date": datetime.date(2022, 7, 28),
            "outcome": 0.0,
            "estimated_prior": 0.35,
            "contamination_risk": 3,
        },
        {
            "question": "Will FTX file for bankruptcy in 2022?",
            "resolution_criteria": "FTX Trading Ltd files for Chapter 11",
            "date_created": datetime.date(2022, 11, 8),
            "resolution_date": datetime.date(2022, 11, 11),
            "outcome": 1.0,
            "estimated_prior": 0.60,
            "contamination_risk": 2,
        },
        {
            "question": "Will US median home sale prices decline year-over-year in 2023?",
            "resolution_criteria": "NAR or Redfin reports YoY national median home price decline for any quarter",
            "date_created": datetime.date(2023, 1, 1),
            "resolution_date": datetime.date(2023, 12, 31),
            "outcome": 0.0,
            "estimated_prior": 0.55,
            "contamination_risk": 2,
        },
        {
            "question": "Will the US national debt exceed $33 trillion by end of 2023?",
            "resolution_criteria": "US Treasury Debt to the Penny tracker shows $33T+",
            "date_created": datetime.date(2023, 1, 1),
            "resolution_date": datetime.date(2023, 9, 18),
            "outcome": 1.0,
            "estimated_prior": 0.72,
            "contamination_risk": 1,
        },
        # 🤖 Technology & AI (10 questions)
        {
            "question": "Will OpenAI release GPT-4 publicly before July 2023?",
            "resolution_criteria": "GPT-4 made available to API customers or via ChatGPT",
            "date_created": datetime.date(2023, 1, 1),
            "resolution_date": datetime.date(2023, 3, 14),
            "outcome": 1.0,
            "estimated_prior": 0.55,
            "contamination_risk": 3,
        },
        {
            "question": 'Will Twitter change its name or brand to something other than "Twitter" in 2023?',
            "resolution_criteria": "Twitter Inc. rebrands or renames its core platform",
            "date_created": datetime.date(2023, 6, 1),
            "resolution_date": datetime.date(2023, 7, 23),
            "outcome": 1.0,
            "estimated_prior": 0.30,
            "contamination_risk": 3,
        },
        {
            "question": "Will Meta release an open-source large language model with 70B+ parameters in 2023?",
            "resolution_criteria": "Meta publicly releases model weights with permissive license",
            "date_created": datetime.date(2023, 3, 1),
            "resolution_date": datetime.date(2023, 7, 18),
            "outcome": 1.0,
            "estimated_prior": 0.40,
            "contamination_risk": 2,
        },
        {
            "question": "Will Netflix lose paying subscribers in Q1 2022 (first time in over a decade)?",
            "resolution_criteria": "Netflix Q1 2022 earnings report shows net subscriber loss",
            "date_created": datetime.date(2022, 1, 1),
            "resolution_date": datetime.date(2022, 4, 19),
            "outcome": 1.0,
            "estimated_prior": 0.15,
            "contamination_risk": 2,
        },
        {
            "question": "Will Apple's market capitalization reach $3 trillion at any point in 2022?",
            "resolution_criteria": "Apple's market cap hits $3T on any trading day",
            "date_created": datetime.date(2022, 1, 1),
            "resolution_date": datetime.date(2022, 1, 3),
            "outcome": 1.0,
            "estimated_prior": 0.60,
            "contamination_risk": 2,
        },
        {
            "question": "Will Elon Musk complete the acquisition of Twitter for ~$44B by end of 2022?",
            "resolution_criteria": "Deal closes and Musk takes ownership",
            "date_created": datetime.date(2022, 7, 12),
            "resolution_date": datetime.date(2022, 10, 27),
            "outcome": 1.0,
            "estimated_prior": 0.40,
            "contamination_risk": 3,
        },
        {
            "question": "Will Google release a publicly available large language model/chatbot in 2023 that directly competes with ChatGPT?",
            "resolution_criteria": "Google launches Bard or equivalent product to the public",
            "date_created": datetime.date(2023, 1, 1),
            "resolution_date": datetime.date(2023, 3, 21),
            "outcome": 1.0,
            "estimated_prior": 0.80,
            "contamination_risk": 3,
        },
        {
            "question": "Will any AI system score above 85% on the MMLU benchmark by end of 2022?",
            "resolution_criteria": "Published peer-reviewed or credible technical report showing ≥85% on MMLU",
            "date_created": datetime.date(2022, 1, 1),
            "resolution_date": datetime.date(2022, 12, 31),
            "outcome": 0.0,
            "estimated_prior": 0.20,
            "contamination_risk": 1,
        },
        {
            "question": "Will Starlink achieve 1 million active subscribers by end of 2022?",
            "resolution_criteria": "SpaceX or credible source reports 1M+ active Starlink users",
            "date_created": datetime.date(2022, 1, 1),
            "resolution_date": datetime.date(2022, 12, 31),
            "outcome": 1.0,
            "estimated_prior": 0.55,
            "contamination_risk": 1,
        },
        {
            "question": "Will Apple release a major AI-focused product or feature under its own AI brand in 2024?",
            "resolution_criteria": "Apple announces branded AI product/feature at WWDC or major event",
            "date_created": datetime.date(2024, 1, 1),
            "resolution_date": datetime.date(2024, 6, 10),
            "outcome": 1.0,
            "estimated_prior": 0.72,
            "contamination_risk": 3,
        },
        # 🏥 Health & Medicine (8 questions)
        {
            "question": "Will a COVID-19 vaccine demonstrate ≥90% efficacy in Phase 3 trials by end of 2020?",
            "resolution_criteria": "Any vaccine reports ≥90% efficacy in published Phase 3 data",
            "date_created": datetime.date(2020, 9, 1),
            "resolution_date": datetime.date(2020, 11, 9),
            "outcome": 1.0,
            "estimated_prior": 0.12,
            "contamination_risk": 3,
        },
        {
            "question": "Will the FDA grant full (non-emergency) approval to a COVID-19 vaccine by end of 2021?",
            "resolution_criteria": "FDA issues Biologics License Application approval",
            "date_created": datetime.date(2021, 6, 1),
            "resolution_date": datetime.date(2021, 8, 23),
            "outcome": 1.0,
            "estimated_prior": 0.55,
            "contamination_risk": 2,
        },
        {
            "question": "Will COVID-19 deaths in the US exceed 500,000 by end of 2021?",
            "resolution_criteria": "CDC reports 500,000+ cumulative COVID deaths",
            "date_created": datetime.date(2021, 1, 1),
            "resolution_date": datetime.date(2021, 2, 22),
            "outcome": 1.0,
            "estimated_prior": 0.65,
            "contamination_risk": 3,
        },
        {
            "question": "Will the WHO declare the COVID-19 Public Health Emergency of International Concern (PHEIC) over in 2023?",
            "resolution_criteria": "WHO Director-General formally ends the PHEIC declaration",
            "date_created": datetime.date(2023, 1, 1),
            "resolution_date": datetime.date(2023, 5, 5),
            "outcome": 1.0,
            "estimated_prior": 0.60,
            "contamination_risk": 2,
        },
        {
            "question": "Will the FDA approve a drug specifically targeting Alzheimer's disease progression (not just symptoms) by end of 2023?",
            "resolution_criteria": "FDA grants traditional or accelerated approval to a disease-modifying Alzheimer's drug",
            "date_created": datetime.date(2023, 1, 1),
            "resolution_date": datetime.date(2023, 7, 6),
            "outcome": 1.0,
            "estimated_prior": 0.40,
            "contamination_risk": 1,
        },
        {
            "question": "Will a new COVID variant classified as a Variant of Concern by WHO emerge in the second half of 2021?",
            "resolution_criteria": "WHO designates a new VoC after June 2021",
            "date_created": datetime.date(2021, 6, 1),
            "resolution_date": datetime.date(2021, 11, 26),
            "outcome": 1.0,
            "estimated_prior": 0.55,
            "contamination_risk": 2,
        },
        {
            "question": "Will US life expectancy decline for a second consecutive year in 2021 (following the 2020 decline)?",
            "resolution_criteria": "CDC National Center for Health Statistics reports lower life expectancy for 2021 vs. 2020",
            "date_created": datetime.date(2021, 6, 1),
            "resolution_date": datetime.date(2022, 8, 31),
            "outcome": 1.0,
            "estimated_prior": 0.60,
            "contamination_risk": 1,
        },
        {
            "question": "Will the US require COVID vaccine proof for domestic air travel at any point in 2021?",
            "resolution_criteria": "TSA or executive order mandates domestic vaccine proof for air travel",
            "date_created": datetime.date(2021, 9, 1),
            "resolution_date": datetime.date(2021, 12, 31),
            "outcome": 0.0,
            "estimated_prior": 0.30,
            "contamination_risk": 2,
        },
        # ⚡ Energy & Climate (6 questions)
        {
            "question": "Will Brent crude oil exceed $100/barrel at any point in 2022?",
            "resolution_criteria": "Brent spot price reaches $100+ on any trading day",
            "date_created": datetime.date(2022, 1, 1),
            "resolution_date": datetime.date(2022, 2, 24),
            "outcome": 1.0,
            "estimated_prior": 0.30,
            "contamination_risk": 3,
        },
        {
            "question": "Will the US pass major climate legislation (IRA or equivalent) in 2022?",
            "resolution_criteria": "President signs into law a bill with substantial clean energy provisions",
            "date_created": datetime.date(2022, 6, 1),
            "resolution_date": datetime.date(2022, 8, 16),
            "outcome": 1.0,
            "estimated_prior": 0.20,
            "contamination_risk": 2,
        },
        {
            "question": "Will the EU formally adopt an embargo on Russian seaborne oil in 2022?",
            "resolution_criteria": "EU Council approves sanctions package banning Russian oil imports",
            "date_created": datetime.date(2022, 5, 1),
            "resolution_date": datetime.date(2022, 6, 3),
            "outcome": 1.0,
            "estimated_prior": 0.65,
            "contamination_risk": 2,
        },
        {
            "question": "Will global CO2 emissions reach or exceed 2019 (pre-COVID) levels by end of 2022?",
            "resolution_criteria": "IEA or similar credible source reports 2022 emissions ≥ 2019 levels",
            "date_created": datetime.date(2022, 1, 1),
            "resolution_date": datetime.date(2023, 3, 2),
            "outcome": 1.0,
            "estimated_prior": 0.62,
            "contamination_risk": 1,
        },
        {
            "question": "Will any US state generate more than 50% of its electricity from wind and solar in 2022?",
            "resolution_criteria": "EIA data shows a state averaging 50%+ wind+solar share for full year 2022",
            "date_created": datetime.date(2022, 1, 1),
            "resolution_date": datetime.date(2023, 6, 1),
            "outcome": 1.0,
            "estimated_prior": 0.55,
            "contamination_risk": 1,
        },
        {
            "question": "Will Texas's power grid experience a major failure (rolling blackouts affecting 1M+ customers) in winter 2021?",
            "resolution_criteria": "ERCOT implements controlled blackouts affecting at least 1 million customers",
            "date_created": datetime.date(2021, 2, 10),
            "resolution_date": datetime.date(2021, 2, 15),
            "outcome": 1.0,
            "estimated_prior": 0.25,
            "contamination_risk": 2,
        },
        # 🚀 Space & Science (6 questions)
        {
            "question": "Will the James Webb Space Telescope launch before end of 2021?",
            "resolution_criteria": "JWST successfully launches from Kourou",
            "date_created": datetime.date(2021, 6, 1),
            "resolution_date": datetime.date(2021, 12, 25),
            "outcome": 1.0,
            "estimated_prior": 0.55,
            "contamination_risk": 2,
        },
        {
            "question": "Will NASA's Artemis I uncrewed lunar mission launch in 2022?",
            "resolution_criteria": "Artemis I SLS rocket launches (any date in 2022)",
            "date_created": datetime.date(2022, 6, 1),
            "resolution_date": datetime.date(2022, 11, 16),
            "outcome": 1.0,
            "estimated_prior": 0.50,
            "contamination_risk": 2,
        },
        {
            "question": "Will SpaceX's Starship complete its first full integrated flight test (both stages) in 2023?",
            "resolution_criteria": "IFT-1 launches (reaching space or not) with both booster and ship",
            "date_created": datetime.date(2023, 1, 1),
            "resolution_date": datetime.date(2023, 4, 20),
            "outcome": 1.0,
            "estimated_prior": 0.55,
            "contamination_risk": 2,
        },
        {
            "question": "Will SpaceX successfully catch the Starship booster (Super Heavy) with the launch tower arms in 2024?",
            "resolution_criteria": '"Mechazilla" chopstick arms catch the booster on a flight test',
            "date_created": datetime.date(2024, 6, 1),
            "resolution_date": datetime.date(2024, 10, 13),
            "outcome": 1.0,
            "estimated_prior": 0.30,
            "contamination_risk": 1,
        },
        {
            "question": "Will JWST's first full-color science images be publicly released before end of 2022?",
            "resolution_criteria": "NASA publicly releases JWST science images",
            "date_created": datetime.date(2022, 3, 1),
            "resolution_date": datetime.date(2022, 7, 12),
            "outcome": 1.0,
            "estimated_prior": 0.82,
            "contamination_risk": 2,
        },
        {
            "question": "Will NASA's DART mission successfully alter the orbit of asteroid Dimorphos?",
            "resolution_criteria": "Post-impact measurements confirm orbital period changed",
            "date_created": datetime.date(2022, 9, 27),
            "resolution_date": datetime.date(2022, 10, 11),
            "outcome": 1.0,
            "estimated_prior": 0.72,
            "contamination_risk": 1,
        },
        # ⚽ Sports (4 questions)
        {
            "question": "Will Argentina win the 2022 FIFA World Cup?",
            "resolution_criteria": "Argentina lifts the trophy",
            "date_created": datetime.date(2022, 11, 1),
            "resolution_date": datetime.date(2022, 12, 18),
            "outcome": 1.0,
            "estimated_prior": 0.18,
            "contamination_risk": 3,
        },
        {
            "question": "Will the Los Angeles Rams win Super Bowl LVI (Feb 2022)?",
            "resolution_criteria": "Rams win the game",
            "date_created": datetime.date(2022, 2, 1),
            "resolution_date": datetime.date(2022, 2, 13),
            "outcome": 1.0,
            "estimated_prior": 0.55,
            "contamination_risk": 2,
        },
        {
            "question": "Will the Denver Nuggets win the 2023 NBA Championship?",
            "resolution_criteria": "Nuggets win the Finals",
            "date_created": datetime.date(2023, 5, 1),
            "resolution_date": datetime.date(2023, 6, 12),
            "outcome": 1.0,
            "estimated_prior": 0.30,
            "contamination_risk": 2,
        },
        {
            "question": "Will Novak Djokovic win the 2023 US Open men's singles title?",
            "resolution_criteria": "Djokovic wins the US Open",
            "date_created": datetime.date(2023, 8, 25),
            "resolution_date": datetime.date(2023, 9, 10),
            "outcome": 1.0,
            "estimated_prior": 0.35,
            "contamination_risk": 2,
        },
    ]
}


def baseline_forecasting():
    pass


if __name__ == "__main__":
    baseline_forecasting()
